function u(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function v(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:u(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var w="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a};
function x(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");}var y=x(this);function A(a,b){if(b)a:{var e=y;a=a.split(".");for(var f=0;f<a.length-1;f++){var k=a[f];if(!(k in e))break a;e=e[k]}a=a[a.length-1];f=e[a];b=b(f);b!=f&&null!=b&&w(e,a,{configurable:!0,writable:!0,value:b})}}
function B(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.o=0;this.j=null}function C(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}B.prototype.m=function(a){this.i=a};function D(a,b){a.j={F:b,G:!0};a.g=a.o}B.prototype.return=function(a){this.j={return:a};this.g=this.o};function E(a,b,e){a.g=e;return{value:b}}function F(a){this.g=new B;this.h=a}
function N(a,b){C(a.g);var e=a.g.h;if(e)return P(a,"return"in e?e["return"]:function(f){return{value:f,done:!0}},b,a.g.return);a.g.return(b);return Q(a)}function P(a,b,e,f){try{var k=b.call(a.g.h,e);if(!(k instanceof Object))throw new TypeError("Iterator result "+k+" is not an object");if(!k.done)return a.g.l=!1,k;var n=k.value}catch(c){return a.g.h=null,D(a.g,c),Q(a)}a.g.h=null;f.call(a.g,n);return Q(a)}
function Q(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(e){a.g.i=void 0,D(a.g,e)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.G)throw b.F;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function R(a){this.next=function(b){C(a.g);a.g.h?b=P(a,a.g.h.next,b,a.g.m):(a.g.m(b),b=Q(a));return b};this.throw=function(b){C(a.g);a.g.h?b=P(a,a.g.h["throw"],b,a.g.m):(D(a.g,b),b=Q(a));return b};this.return=function(b){return N(a,b)};this[Symbol.iterator]=function(){return this}}function S(a){function b(f){return a.next(f)}function e(f){return a.throw(f)}return new Promise(function(f,k){function n(c){c.done?f(c.value):Promise.resolve(c.value).then(b,e).then(n,k)}n(a.next())})}
function T(a){return S(new R(new F(a)))}A("Symbol",function(a){function b(n){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new e(f+(n||"")+"_"+k++,n)}function e(n,c){this.g=n;w(this,"description",{configurable:!0,writable:!0,value:c})}if(a)return a;e.prototype.toString=function(){return this.g};var f="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",k=0;return b});
A("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),e=0;e<b.length;e++){var f=y[b[e]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&w(f.prototype,a,{configurable:!0,writable:!0,value:function(){return U(u(this))}})}return a});function U(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
A("Promise",function(a){function b(c){this.h=0;this.i=void 0;this.g=[];this.o=!1;var d=this.j();try{c(d.resolve,d.reject)}catch(g){d.reject(g)}}function e(){this.g=null}function f(c){return c instanceof b?c:new b(function(d){d(c)})}if(a)return a;e.prototype.h=function(c){if(null==this.g){this.g=[];var d=this;this.i(function(){d.l()})}this.g.push(c)};var k=y.setTimeout;e.prototype.i=function(c){k(c,0)};e.prototype.l=function(){for(;this.g&&this.g.length;){var c=this.g;this.g=[];for(var d=0;d<c.length;++d){var g=
c[d];c[d]=null;try{g()}catch(h){this.j(h)}}}this.g=null};e.prototype.j=function(c){this.i(function(){throw c;})};b.prototype.j=function(){function c(h){return function(l){g||(g=!0,h.call(d,l))}}var d=this,g=!1;return{resolve:c(this.A),reject:c(this.l)}};b.prototype.A=function(c){if(c===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof b)this.C(c);else{a:switch(typeof c){case "object":var d=null!=c;break a;case "function":d=!0;break a;default:d=!1}d?this.v(c):this.m(c)}};
b.prototype.v=function(c){var d=void 0;try{d=c.then}catch(g){this.l(g);return}"function"==typeof d?this.D(d,c):this.m(c)};b.prototype.l=function(c){this.u(2,c)};b.prototype.m=function(c){this.u(1,c)};b.prototype.u=function(c,d){if(0!=this.h)throw Error("Cannot settle("+c+", "+d+"): Promise already settled in state"+this.h);this.h=c;this.i=d;2===this.h&&this.B();this.H()};b.prototype.B=function(){var c=this;k(function(){if(c.O()){var d=y.console;"undefined"!==typeof d&&d.error(c.i)}},1)};b.prototype.O=
function(){if(this.o)return!1;var c=y.CustomEvent,d=y.Event,g=y.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof c?c=new c("unhandledrejection",{cancelable:!0}):"function"===typeof d?c=new d("unhandledrejection",{cancelable:!0}):(c=y.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.i;return g(c)};b.prototype.H=function(){if(null!=this.g){for(var c=0;c<this.g.length;++c)n.h(this.g[c]);this.g=null}};var n=new e;b.prototype.C=
function(c){var d=this.j();c.s(d.resolve,d.reject)};b.prototype.D=function(c,d){var g=this.j();try{c.call(d,g.resolve,g.reject)}catch(h){g.reject(h)}};b.prototype.then=function(c,d){function g(q,r){return"function"==typeof q?function(m){try{h(q(m))}catch(p){l(p)}}:r}var h,l,t=new b(function(q,r){h=q;l=r});this.s(g(c,h),g(d,l));return t};b.prototype.catch=function(c){return this.then(void 0,c)};b.prototype.s=function(c,d){function g(){switch(h.h){case 1:c(h.i);break;case 2:d(h.i);break;default:throw Error("Unexpected state: "+
h.h);}}var h=this;null==this.g?n.h(g):this.g.push(g);this.o=!0};b.resolve=f;b.reject=function(c){return new b(function(d,g){g(c)})};b.race=function(c){return new b(function(d,g){for(var h=v(c),l=h.next();!l.done;l=h.next())f(l.value).s(d,g)})};b.all=function(c){var d=v(c),g=d.next();return g.done?f([]):new b(function(h,l){function t(m){return function(p){q[m]=p;r--;0==r&&h(q)}}var q=[],r=0;do q.push(void 0),r++,f(g.value).s(t(q.length-1),l),g=d.next();while(!g.done)})};return b});function V(a,b){var e,f,k,n,c,d,g,h,l,t,q,r,m,p,G,H,I,J,K,L,M,O;T(function(z){if(1==z.g)return b.innerText="",e=document.createElement("table"),b.appendChild(e),e.style.borderCollapse="collapse",f=document.createElement("thead"),e.appendChild(f),f.appendChild(document.createElement("td")).innerText="Name",f.appendChild(document.createElement("td")).innerText="Scale",f.appendChild(document.createElement("td")).innerText="m",f.appendChild(document.createElement("td")).innerText="kg",f.appendChild(document.createElement("td")).innerText=
"s",f.appendChild(document.createElement("td")).innerText="A",f.appendChild(document.createElement("td")).innerText="K",f.appendChild(document.createElement("td")).innerText="mol",f.appendChild(document.createElement("td")).innerText="cd",E(z,a.json(),2);k=z.i;n=k.types;c=k.units;d=e.appendChild(document.createElement("tbody"));for(g in n)for(h=!0,l=n[g],t=v(l),q=t.next();!q.done;q=t.next())if(r=q.value,m=c[r])p=document.createElement("tr"),d.appendChild(p),p.appendChild(document.createElement("td")).innerText=
r,p.appendChild(document.createElement("td")).innerText=m.scale,h&&(h=!1,p.classList.add("firstrow"),G=p.appendChild(document.createElement("td")),H=p.appendChild(document.createElement("td")),I=p.appendChild(document.createElement("td")),J=p.appendChild(document.createElement("td")),K=p.appendChild(document.createElement("td")),L=p.appendChild(document.createElement("td")),M=p.appendChild(document.createElement("td")),O=p.appendChild(document.createElement("td")),G.classList.add("min_width"),H.classList.add("min_width"),
I.classList.add("min_width"),J.classList.add("min_width"),K.classList.add("min_width"),L.classList.add("min_width"),M.classList.add("min_width"),m.L&&(G.innerText=m.L),m.M&&(H.innerText=m.M),m.T&&(I.innerText=m.T),m.I&&(J.innerText=m.I),m.K&&(K.innerText=m.K),m.N&&(L.innerText=m.N),m.J&&(M.innerText=m.J),O.innerText=g);z.g=0})}
function W(a){var b,e,f,k,n;return T(function(c){if(1==c.g){b=document.getElementById("output");if(a.ok)return E(c,a.json(),5);e=JSON;f=e.parse;return E(c,a.text(),4)}if(5!=c.g)k=f.call(e,c.i),b.innerHTML="",b.appendChild(document.createElement("pre")).innerText=k.errors;else{var d=n=c.i;b.innerHTML="";var g=b.appendChild(document.createElement("table"));g.border=1;var h=g.appendChild(document.createElement("thead")).appendChild(document.createElement("tr"));h.appendChild(document.createElement("th")).innerText=
"Name ";h.appendChild(document.createElement("th")).innerText="Value ";h.appendChild(document.createElement("th")).innerText="Units ";g=g.appendChild(document.createElement("tbody"));d=v(d.values);for(h=d.next();!h.done;h=d.next()){h=h.value;var l=g.appendChild(document.createElement("tr")),t=l.appendChild(document.createElement("td")),q=l.appendChild(document.createElement("td"));l=l.appendChild(document.createElement("td"));"name"in h&&(t.innerText=h.name);"value"in h&&(q.innerText=h.value);"unit"in
h&&(l.innerText=h.unit)}}c.g=0})};fetch("/preamble.tbd").then(function(a){var b;return T(function(e){if(1==e.g)return b=document.getElementById("preamble"),E(e,a.text(),2);b.innerText=e.i;e.g=0})});fetch("/units").then(function(a){var b;return T(function(e){b=document.getElementById("units");V(a,b);e.g=0})});document.getElementById("submit_script").onclick=function(){var a=document.getElementById("input_script");fetch("/json",{method:"POST",body:a.value}).then(W)};
